version: "3.7"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    ulimits:
      nofile: 262144
  java:
    build:
      context: ./
    volumes:
      - ./:/app
      - .m2/:/root/.m2
    command: bash -c "./mvnw spring-boot:run"
    # tty: true
    environment:
      DATASOURCE_URL: 'mysql://localhost:3306/personal-finances'
      DATASOURCE_USERNAME: 'root'
      DATASOURCE_PASSWORD: 'admin'
      PORT: '8080'
      DDL_AUTO: 'update'
      VERSION: '0.0.1-SNAPSHOT'
    network_mode: host
