version: "3.7"
services:
  java:
    image: diegton/personal-finances-spring:latest
    command: bash start.sh
    environment:
      DATASOURCE-URL: 'mysql://localhost:3306/personal-finances'
      DATASOURCE-USERNAME: 'root'
      DATASOURCE-PASSWORD: 'admin'
      PORT: '8090'
      DDL-AUTO: 'none'
      VERSION: '0.0.1-SNAPSHOT'
    network_mode: host
